project:
    analysers:
        enabled:
            - '*'
        disabled:
            - 'docblock'
    directories:
        include:
            - 'src/'
        exclude:
            - 'tests/'
            - 'vendor/'
